#!/bin/bash

# Base URL for the API
BASE_URL="http://localhost:8000"

# IMPORTANT: Replace "YOUR_REAL_TOKEN_HERE" with an actual token generated by the API.
# You can get a real token by running test.sh or by manually calling the /token/generate/ endpoint.
REAL_TOKEN="3_KD_EQSijdD5kFTevujpUmQGpZ5fbJ-bSR4n9AlOHQ" 

echo "Starting real token check with curl..."
echo "-------------------------------------"

# Test: Check a real token
echo "Test: Checking a real token"
if [ "$REAL_TOKEN" == "YOUR_REAL_TOKEN_HERE" ]; then
  echo "Error: Please replace 'YOUR_REAL_TOKEN_HERE' with an actual token in check_real_token.sh"
else
  curl -s -X POST \
    -H "Content-Type: application/json" \
    -d "{\"token\": \"$REAL_TOKEN\"}" \
    "$BASE_URL/token/check/"
fi
echo -e "\n"

echo "-------------------------------------"
echo "Real token check finished."